# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/green_area_calculator_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GreenAreaCalculatorDialog(object):
    def setupUi(self, GreenAreaCalculatorDialog):
        GreenAreaCalculatorDialog.setObjectName("GreenAreaCalculatorDialog")
        GreenAreaCalculatorDialog.resize(500, 220)
        self.verticalLayout = QtWidgets.QVBoxLayout(GreenAreaCalculatorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_sectors = QtWidgets.QLabel(GreenAreaCalculatorDialog)
        self.label_sectors.setObjectName("label_sectors")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_sectors)
        self.cbo_sectors = QtWidgets.QComboBox(GreenAreaCalculatorDialog)
        self.cbo_sectors.setObjectName("cbo_sectors")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbo_sectors)
        self.label_veg = QtWidgets.QLabel(GreenAreaCalculatorDialog)
        self.label_veg.setObjectName("label_veg")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_veg)
        self.cbo_vegetation = QtWidgets.QComboBox(GreenAreaCalculatorDialog)
        self.cbo_vegetation.setObjectName("cbo_vegetation")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbo_vegetation)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.btn_calculate = QtWidgets.QPushButton(GreenAreaCalculatorDialog)
        self.btn_calculate.setEnabled(False)
        self.btn_calculate.setObjectName("btn_calculate")
        self.buttonsLayout.addWidget(self.btn_calculate)
        self.btn_close = QtWidgets.QPushButton(GreenAreaCalculatorDialog)
        self.btn_close.setObjectName("btn_close")
        self.buttonsLayout.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(GreenAreaCalculatorDialog)
        QtCore.QMetaObject.connectSlotsByName(GreenAreaCalculatorDialog)

    def retranslateUi(self, GreenAreaCalculatorDialog):
        _translate = QtCore.QCoreApplication.translate
        GreenAreaCalculatorDialog.setWindowTitle(_translate("GreenAreaCalculatorDialog", "Green Area Calculator"))
        self.label_sectors.setText(_translate("GreenAreaCalculatorDialog", "Census Sectors Layer:"))
        self.label_veg.setText(_translate("GreenAreaCalculatorDialog", "Vegetation Layer:"))
        self.btn_calculate.setText(_translate("GreenAreaCalculatorDialog", "Calculate"))
        self.btn_close.setText(_translate("GreenAreaCalculatorDialog", "Close"))
